### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by ontrou** [Thiews/Obsidian-Harmonic#1]
I've used [SlRvb's CSS snippet for checkboxes](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/S%20-%20Checkboxes.css) with other themes, but it doesn't seem to play well with Harmonic. Is this something you can provide with your theme?
The snippet styles include these variations (and a lot more in fact):
- [-]
- [>]
- [?]
- [/]

**Comment by Thiews** [comment]
Hi !! I can try to do that ! Do you have an image to see how the checkboxes are displayed ?

**Comment by Thiews** [comment]
I just done something for preview mode. I added
- [L] for late
- [I] for important

**Comment by ontrou** [comment]
Oh this looks so nice! Everything coordinates with the theme. [I] Important is even bold and all-cap. A nice touch. 


Not sure if you still want an image.… this comes from [this post](https://forum.obsidian.md/t/creating-tasks-that-have-three-possible-states-instead-of-two/24105/2)
![death_au checkboxes](https://forum.obsidian.md/uploads/default/original/3X/1/f/1fa3b37f78d6a341ceef422f684909cf1766a0f2.png)

**Comment by Thiews** [comment]
Everything is fine for you ?

**Comment by ontrou** [comment]
yes
