### ISSUE TITLE
turn off frameless?

### ISSUE THREAD

**Issue by chad-bennett** [Thiews/Obsidian-Harmonic#2]
Absolutely loving Harmonic theme. For some reason, it turns on frameless mode by default. I would like to have the titlebar back. 

I've been working through css files and style settings. I've narrowed it down to the theme somehow because the titlebar is visible in other themes. Where can I go to toggle the titlebar back on?

**Comment by Thiews** [comment]
Hi !! You can update the theme, I added an "activate frameless mode" in Style settings plugin > Focus mode ! Is that ok ?

**Comment by chad-bennett** [comment]
Wow. Quick response. It works just as I had hoped. You rock!
