### ISSUE TITLE
H5 font-size cannot be customized

### ISSUE THREAD

**Issue by LilaRest** [Thiews/Obsidian-Harmonic#3]
Hi !
When I try to change the h5 font-size in "Style Settings > Harmonic > Headings > Level 5", nothing happens. The h5 font-size is fixed to the default value "1.12em".
I've opened the dev console and it seems that you've just forgotten `font-size: var(--h5);` in the style of ".cm-header-5".
I could have made a pull request with the change but I thought it would be faster for you to just add the missing line rather than handling a pull request.

Thanks for this great theme !
Lilian :slightly_smiling_face:

**Comment by Thiews** [comment]
Hi !! Thanks to notice that ! Try to update the theme , it should be ok ! Tell me if that's working ;)

**Comment by LilaRest** [comment]
> Hi !! Thanks to notice that ! Try to update the theme , it should be ok ! Tell me if that's working ;)
All works fine, in preview and in edit mode. Thank you ! :)
