### ISSUE TITLE
Proposal : Split the theme's CSS sheet in multiple CSS sheets

### ISSUE THREAD

**Issue by LilianCr** [Thiews/Obsidian-Harmonic#5]
The goal is to allow easier collaboration on the theme :
- People can work on different files without conflicts
- The project is more accessible and easier to understand for new contributors
- It's easier to maintain in the long term

But, is it possible with Obsidian ? 
Have you tried it ? @Thiews 
If we create a CSS file that imports several other CSS files, will Obsidian import them when someone downloads the theme ? Or does it only allow one CSS file ?

I'm going to open an issue on the Obsidian repo.
Lilian :slightly_smiling_face:

**Comment by Thiews** [comment]
I think that should be possible with @import url("file.css")

**Comment by LilaRest** [comment]
Yes in CSS it's technically possible but will Obsidian import the multiple files when someone installs the theme ?

**Comment by Thiews** [comment]
We can try if you put a css file in your repository and I make a link to it in the theme css file

**Comment by LilaRest** [comment]
Here is the topic I've created on the Obsidian's forum : https://forum.obsidian.md/t/is-it-possible-to-split-one-theme-css-sheet-obsidian-css-in-multiple-css-sheets/29278

**Comment by LilaRest** [comment]
> We can try if you put a css file in your repository and I make a link to it in the theme css file

Do you mean importing an external file ? (`@import("https://mydomain.com/my-external-file.css")`)

**Comment by Thiews** [comment]
Yes ..

**Comment by LilaRest** [comment]
> Yes ..

It means that every people that use Obsidian offline will have a broken theme, I think a proper way to achieve that should exist.
Someone answered on my forum's topic : 
> **alltagsverstand** : I don’t know if (and I currently don’t think that…) you can use something like an import function. Yet, you can work with css snippets which you can individually activate.

I've in mind another solution to have multiple CSS files : Creating a script, for example named `bundle_and_push.bash` that bundles all the CSS files in the obsidian.css file and then initiate the Github push. What do you think about this idea ?

**Comment by Thiews** [comment]
After thinking about it, I think the best way to do it is to create a css snippet repository in Harmonic GitHub page. Users could be able to install snippets if they want.

**Comment by LilaRest** [comment]
> After thinking about it, I think the best way to do it is to create a css snippet repository in Harmonic GitHub page. Users could be able to install snippets if they want.

How would it work in practice? 
What would happen when someone installs the Harmonic theme?
What would be in those snippets?

**Comment by Thiews** [comment]
I think that the code that improves readability (as you did) should be integrated directly in the obsidian.css by pull requests. Other custom css option (more specifics) that some would like to add could be added in a snippet repository, to let the user choose if he wants to install it...

**Comment by LilaRest** [comment]
Oh I think you didn't understand what I meant, I copy/paste my last forum's message, perhaps that will help you to understand :



Actually all the themes I know are only built with one CSS file called obsidian.css
For example the Harmonic Theme where you can see that there is obsidian.css file with 6143 lines !!

So my goal is to be able to split this obsidian.css file in several files to to allow easier collaboration on the theme :

- People can work on different files without conflicts
- The project is more accessible and easier to understand for new contributors
- It’s easier to maintain in the long term

For example to transform this alone obsidian.css file in :

- main.css (the main file that import all others CSS files)
- left-sidebar.css (the CSS file that style the left sidebar)
- right-sidebar.css (the CSS file that style the right sidebar)
- notes.css (the CSS file that style the notes in edit and preview mode)
- etc.

**Comment by LilaRest** [comment]
And if you want, we could have a short phone call and I could explain it to you **in French** :yum:. It seems easier to me

**Comment by Thiews** [comment]
haha ! Je n'avais effectivement pas vu ton commentaire sur le post ! J'aime bien l'idée mais si plusieurs personnes veulent faire des modifications différentes sur le même fichier css (par ex left-sidebar.css), ça peut compliquer le truc ! La question est de savoir si les fichiers css servent simplement à scinder le code pour le rendre plus lisible ou si c'est pour ajouter des options de customization (dans ce cas les snippets sont à mon avis plus adaptés !)

**Comment by LilaRest** [comment]
Oui pour moi c'est simplement scinder le code pour le rendre plus lisible. Pour les options de customisation, je suis d'accord que les snippets ou le plugin **Style Settings** (que tu utilises déjà) sont plus adaptés.

Et par rapport aux conflits lors de modifications différentes sur le même fichier, scinder le code permet justement de réduire les conflits. 
Actuellement tout est sous le même fichier CSS `obsidian.css` et toute modification, qu'elle soit à propos du style d'une sidebar, à propos du style des notes, à propos des polices et des couleurs se fait dans le même fichier. Il suffit donc que deux personnes contribuent au thème au même moment pour qu'il y ait un possible conflit.
Si on scindait le style en plusieurs fichiers je pourrai par exemple bosser sur le style des sidebars (dans un fichier `sidebars.css` par exemple) pendant que tu bosses sur l'affichage des notes (dans un fichier `notes.css` par exemple) et on pourrait tous les deux pousser nos modifs sans avoir à gérer des possibles conflits.
Puis du coup ce serait tellement plus lisible d'avoir 20-30 fichiers de 200 lignes de CSS plutôt qu'un gros fichier unique qui fait 6000 lignes :rofl:

**Comment by Thiews** [comment]
Oui c'est sûr !! Le problème c'est quand 2 personnes ne sont pas d'accord sur la modification du même fichier. Si quelqu'un veut faire une modification sur left-sidebar.css et qu'une autre personne veut faire différemment....

**Comment by LilaRest** [comment]
> Oui c'est sûr !! Le problème c'est quand 2 personnes ne sont pas d'accord sur la modification du même fichier. Si quelqu'un veut faire une modification sur left-sidebar.css et qu'une autre personne veut faire différemment....

Pour résoudre ce genre de cas (très rare), soit : 
- Tu attends que les personnes qui contribuent à la discussion trouvent ensemble une modification qui leur conviennent à toutes,
  Si elles n'y arrivent pas : 
    - Certaines personnes peuvent décider d'aller contribuer à un projet qui leur ressemble plus,
    - Certaines personnes peuvent créer un fork de ce thème qui partira dans une direction qui leur ressemble plus.
- Tu te places comme modérateur et tu acceptes le pull request qui te semble le mieux, tu merges les deux propositions ou tu refuses les deux.

Et pour le coup ce genre de cas ne dépend pas du fait que le fichier `obsidian.css` soit splité ou non, c'est plutôt un conflit d'idées.
Là moi ce que j'aimerai éviter pour préserver mon temps et mon énergie ce sont les conflis de code, j'aimerai bien contribuer activement à ce thème et je n'ai pas envie de galérer avec des "merge conflicts" à chaque fois que je dois pousser une nouvelle modif hihi :yum:

**Comment by Thiews** [comment]
Je suis d'accord ! On va voir si Obsidian peut gérer plusieurs fichiers css... Par contre, si tu as déjà travaillé sur des améliorations, je peux les intégrer dès maintenant au code.

**Comment by LilaRest** [comment]
Cool ! :)
J'ai commencé à faire une liste des améliorations que j'aimerai apporter mais ne les ai pas encore développé.
Pour moi la priorité c'est du coup de pouvoir avoir un environnement pour contribuer simplement sur ce thème, si tu es ok avec ça je peux me charger de : 
1) Créer une section "How to contribute ?" sur la page d'accueil du repo
2) Voir avec les membres du forum si il est possible de spliter le fichier `obsidian.css` et si ce n'est pas possible créer un script `bundle_and_push.bash` (comme j'en donnais l'idée plus haut)
3) Puis spliter le fichier obsidian.css en plusieurs fichiers

Pi ensuite quand cet environnement sera en place, je développerai les améliorations que j'ai noté :slightly_smiling_face: 
Qu'en penses-tu ?

**Comment by Thiews** [comment]
Avant de bosser dessus, attends de voir si c'est possible !

**Comment by LilaRest** [comment]
Vi :)
Dans tous les cas il y une solution, c'est vrai que si c'était possible ce serait bien plus simple hihi
