### ISSUE TITLE
Improvements for the README.md file

### ISSUE THREAD

**Issue by LilianCr** [Thiews/Obsidian-Harmonic#6]
Hi @Thiews 
I'm currently working on some improvements on the README.md file to make it more simple, readable and clean, you can see it on my forked repo here : https://github.com/LilianCr/Obsidian-Harmonic

I want your approval for something : Can I change images and functionalities presentation ? For example focus mode doesn't require any image, bold and pop could only be a small image in paysage. The goal of that is to make it shorter and easier for everyone that browse the functionalities of the theme :slightly_smiling_face:

**Comment by LilaRest** [comment]
Je me rends compte que je t'ai écrit en anglais... Peut-être qu'on pourrait avoir un autre endroit pour communiquer maintenant que je prévois de contribuer régulièrement au thème ? Ça m'évitera d'ouvrir 50 issues chaque jour :yum: 
As-tu Telegram ou Signal ?

**Comment by Thiews** [comment]
Oui j'ai signal (0661898418) ! Pour README.md, pour simplifier, il faudrait prendre une image et décrire les fonctionnalités qui apparaissent dessus. Je pense que la fonction "writing focus" peut apparaître , j'ai vu quelqu'un qui faisait une vidéo dessus (Curtis McHale). Je me mettrai également une section "contributors".

**Comment by LilaRest** [comment]
> Oui j'ai signal (0661898418) ! Pour README.md, pour simplifier, il faudrait prendre une image et décrire les fonctionnalités qui apparaissent dessus. Je pense que la fonction "writing focus" peut apparaître , j'ai vu quelqu'un qui faisait une vidéo dessus (Curtis McHale). Je me mettrai également une section "contributors".

Je viens de t'envoyer un message, je te répondrai sur Signal pour ce que tu viens de me dire quand j'aurai un peu de temps.
Passe une jolie soirée ! :)
